### PR TITLE
Added getActiveQuarters method to UCSBAPIQuarterService and /api/public/activeQuarters endpoint

### LINKED ISSUE #5: Implement `getActiveQuarterList` method (Backend only)
As a precursor to a future new job that updates all course information for all active quarters at some scheduled interval (e.g. once an hour, once a day, etc.) in this issue you will add a new method to `UCSBAPIQuarterService` called `getActiveQuarterList`  that will return an `ArrayList<String>` value that is a list of the YYYYQ codes starting with the current quarter, and ending with the current value returned by getEndQtrYYYYQ.

You'll also add a endpoint to the `UCSBAPIQuarterController` as follows:

`GET /api/public/activeQuarters` 

the invokes this method and returns the value.

# Details

The `UCSBAPIQuarterService` has these methods:

* `public String getStartQtrYYYYQ()` returns the start quarter for the app in YYYYQ format (i.e. the oldest quarter that is available in the drop down menus in the app).
*  `public String getEndQtrYYYYQ()` returns the start quarter for the app in YYYYQ format (i.e. the newest quarter that is available in the drop down menus in the app, which may be in the future)
* `public String getCurrentQuarterYYYYQ()` gets the current quarter in YYYYQ format.

There is also this method in `models/Quarter.java`

 * `public static List<Quarter> quarterList(String start, String end)` which returns a list of Quarter objects starting at start quarter (specified in YYYYQ format) and ending with end quarter  (specified in YYYYQ format)

Using these tools, and *not* reinventing the wheel, but making as much use of existing methods as possible, add a method to `UCSBAPIQuarterService` called `getActiveQuarterList`  that will return an `ArrayList<String>` value that is a list of the YYYYQ codes starting with the current quarter, and ending with the current value returned by getEndQtrYYYYQ.

For example:

* If the value returned by `getCurrentQuarterYYYYQ` is `20244`  (F24) and the value of END_QTR is `20251` (W25), then the value returned by `getActiveQuarterList` should be `["20244", "20251"]`.
* If the value  returned by `getCurrentQuarterYYYYQ` is `20252`  (S25) and the value of END_QTR is `20254` (F25), then the value returned by `getActiveQuarterList` should be `["20252", "20253", "20254"]`.

# Acceptance Criteria:

- [x] New method implemented as described above
- [x] New controller endpoint implemented as described above

### PR DESCRIPTION
**Pull request by berdly**
closes #5
Adds the requested functionality, cleanly in terms of existing methods!
The endpoint can be entered directly into the browser to test the result!
The deployment can be accessed [here](https://berdly-issue-5.dokku-02.cs.ucsb.edu/)

### CODE REVIEW

**Review by vedp3705 — APPROVED** [review]
Looks right!

**Review by pconrad — COMMENTED** [review]
Code looks good.  But will want to test on dokku before merging.

**Review by pconrad — APPROVED** [review]
LGTM (pending dokku testing)

**Comment by berdly** [comment]
Added deployment!

**Review by raysujf — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
I tried the endpoint and got this as the result.

```
[
  "20244",
  "20243",
  "20242",
  "20241",
  "20234",
  "20233",
  "20232",
  "20231",
  "20224",
  "20223",
  "20222"
]
```

But what we want is every quarter between the current quarter and the END_QTR, which should be: 

```
[
  "20244",
  "20251"
]
```

The idea is that we want the quarters where the data about enrollment and data about what courses are being offered *could still change*.   Quarters *before* the current quarter are not going to change (classes are done, so no one's going to add or drop, and no class is going to be "retroactively added or cancelled" for quarters that are in the past.

So something's wrong here.

**Comment by pconrad** [comment]
> So something's wrong here.

I'm not sure what the problem is, because the code "appears" to be correct.  I wonder if it's the value of END_QTR on your deployment, and perhaps some logic in Quarter.quarterList(getCurrentQuarterYYYYQ(), getEndQtrYYYYQ()) that will make a list in whatever direction you choose?  i.e. maybe the code is correct, but the value of END_QTR is set to a quarter in the past?

I suggest trying to set END_QTR in your deployment to 20251 and seeing if we get the expected result.  Maybe the code is just fine, but it's having an END_QTR that's "in the past" that's creating what "seems" to be a bug?

**Comment by berdly** [comment]
Yes, that's exactly the problem, I redeployed with the new END_QTR and it gives the expected result. I'll change it to return an empty list in the event END_QTR is before current quarter since this implies that there would be no quarters that need to be actively updated.

**Review by leozhu0 — APPROVED** [review]
Looks good!

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
