### PR TITLE
Added Clear Job Logs button to AdminJobsPage

### LINKED ISSUE #9: FEATURE: Allow Admin to Purge Job Log
See also: #48 which is related!

## User Story

* As an admin
* I can purge the job log
* So that old job logs are not cluttering up the job log display and taking up space in the database

### Discussion

At present, the job log grows without bound.

It would be helpful to have a button on the Admin Jobs page labelled "[Purge Job Log]" that would remove all records from the job log table.

### Acceptance Criteria

- [x] The job controller has a DELETE /api/jobs/all route that deletes all jobs from the jobs table.
- [x] There is a "Purge Job Log" button on the job log page that invokes that API call.
- [x] When the Purge Job Log button is clicked, the backend route is called and the job log is cleared out.

### Implementation Todos

Backend:

- [x]  Create the backend route.  You are encouraged to make a separate issue and PR for this backend route.

Frontend:

- [x] Add the button to the page.   Remember in your backendMutation to invalidate the cache key `["/api/jobs/all"]` so that the list of jobs will be refreshed (as it should then be empty).

### PR DESCRIPTION
**Pull request by berdly**
closes #9 
Adds a button onto the Admin JobsPage which can be selected to clear all existing job logs on screen. The issue requested adding backend support through adding an endpoint to delete all jobs in the database, but thankfully, I found that the requested endpoint was already implemented in the repo. I only needed to add a single button.
To test, simply build this branch and login, run some jobs, and clear them!

Deployment can be tested [here](https://berdly-issue-9.dokku-02.cs.ucsb.edu/)

Additionally, I noticed that this implementation and the UpdateGradeInfoForm have an identical implementation. I believe it might be prudent to allow quicker creation of single button tasks like this by refactoring them to both be instances of one component. I've raised the issue in #21.

### CODE REVIEW

**Review by vedp3705 — APPROVED** [review]
Looks good! Consider making that another issue if it seems to work.

**Comment by pconrad** [comment]
@berdly Feedback on your PR description 

1. It currently starts in the middle of the story.    Can you add a sentence or two first describing  what the PR is trying to do?  It's helpful to your code reviews to not make them have to click the link to the issue to understand the purpose of the PR.

2. The first paragraph of what you have, though, is very nice.

3. The second paragraph is also very nice.  I'd suggest improving it by creating an issue to do what you suggest, linking to it, and then discussing it with the team.  FWIW, I think it's a good idea.

**Comment by pconrad** [comment]
@berdly can you create a dokku deployment and link to it from the PR?

**Comment by berdly** [comment]
Added deployment!

**Pull request merged**
